### ISSUE TITLE
回复帖子时的一个bug

### ISSUE THREAD

**Issue by bachue** [ruby-china/ruby-china#238]
几天前就发现的，一直忘记了

我帖子是这么写的：
![screen shot 2013-11-20 at 9 37 40 am](https://f.cloud.github.com/assets/321962/1592560/ceb5ceb2-52bd-11e3-899f-013d8008a52a.png)

但是显示效果却是这么奇葩的，`，叫`这个字符串有什么特别吗？竟然跑到句子最后面去了：
![screen shot 2013-11-20 at 9 37 32 am](https://f.cloud.github.com/assets/321962/1592561/d30ce5c2-52bd-11e3-975b-bf090d2eb608.png)

**Comment by zlx** [comment]
@bachue 中英文之间加上空格就不会有这个问题了

**Comment by huacnlee** [comment]
那是你的问题，请在 URL 后面留空格
