### ISSUE TITLE
Markdown粗体渲染好像有问题

### ISSUE THREAD

**Issue by bachue** [ruby-china/ruby-china#344]
看这个[Topic](https://ruby-china.org/topics/21492)，注意到里面有一句
```markdown
地点：**在浦东陆家嘴的Apple Store旁边**，提早到达的同学请负责占座
```
两个星号中间的内容应该是粗体吧，但是帖子里还是直接输出了，没有经过渲染。
![screen shot 2014-09-11 at 22 21 46](https://cloud.githubusercontent.com/assets/321962/4235398/03e86aca-39bf-11e4-90a3-d29b6968a86d.png)

输入框下面的Guide里写的很清楚
```markdown
支持 Markdown 格式, **粗体**、~~删除线~~、`单行代码`
```

所以应该是一个Bug吧？

**Comment by huacnlee** [comment]
需要左右增加空格
