### ISSUE TITLE
[feature suggest] 关注他人

### ISSUE THREAD

**Issue by zzz6519003** [ruby-china/ruby-china#366]

**Comment by zzz6519003** [comment]
花擦  已经实现了哇！ 是那个pr里面的 我去瞻仰下！
@ashchan 
@huacnlee 
@lgn21st

**Comment by huacnlee** [comment]
https://github.com/ruby-china/ruby-china/commit/6d7f52ffe4696bde491102784103ac29889e83cb

**Comment by zzz6519003** [comment]
:beers:
