### ISSUE TITLE
https://ruby-china.org/account/edit(个人资料设置) Format Validation

### ISSUE THREAD

**Issue by bmiwdmb** [ruby-china/ruby-china#371]
个人资料设置沒有做格式驗証

eg. twitter 帳號可以輸入 @ twitterUserName

view 的 link 會變成：https://twitter.com/%20iwdmb

建議可以驗証一下!

**Comment by huacnlee** [comment]
没必要为了这个增加复杂度，用户填错了，自己会知道的
