### ISSUE TITLE
referer 跳转没有校验

### ISSUE THREAD

**Issue by alsotang** [ruby-china/ruby-china#384]
referer 的跳转应该限定在本站之内。抽出来一个通用函数专门做这事。

**Comment by huacnlee** [comment]
？？ 没明白

**Comment by alsotang** [comment]
不好意思这里没有描述清楚，

https://github.com/ruby-china/ruby-china/blob/f3db7982bf02e393ce550e50dae4da2de4d8bfec/app/controllers/application_controller.rb#L66

这个地方，应该校验一下 referer 的范围。


比如现在先退出 ruby-china，然后从 github.com 跳转过去：
https://ruby-china.org/account/sign_in ，登陆之后，会自动回到 github.com 来

2015-04-17 11:48 GMT+08:00 Jason Lee <notifications@github.com>:
