### ISSUE TITLE
topics/new页面 grouped_collection_select 重复render

### ISSUE THREAD

**Issue by Matrixbirds** [ruby-china/ruby-china#392]
发现 进入topics/new后 
浏览器上点击后退 再点击前进
进来后 grouped_collection_select 会多出一个
@huacnlee

**Comment by Matrixbirds** [comment]
经过进一步的测试发现 只要是select 就会递增式叠加一个出来

**Comment by Matrixbirds** [comment]
https://github.com/ruby-china/ruby-china/pull/393
缓存问题

**Comment by huacnlee** [comment]
问题应该在于 bootstrap-select 的初始化方式上面

**Comment by Matrixbirds** [comment]
浏览器后退和前进读的应该是缓存吧 我在new.html.erb加入js 
后退后再点前进 并没有执行js

**Comment by Matrixbirds** [comment]
@huacnlee

**Comment by huacnlee** [comment]
前进后退根本就没法页面的 HTTP 请求的

**Comment by huacnlee** [comment]
不用 @ 你回复我能看到

**Comment by Matrixbirds** [comment]
soga 既然是读取缓存的话 应该和bootstrap-select没关系吧 怀疑是页面缓存问题
