### ISSUE TITLE
user email 唯一性问题

### ISSUE THREAD

**Issue by Matrixbirds** [ruby-china/ruby-china#394]
当使用github登陆ruby-china的时候 email是无法修改的 那么公开email的特性有何意义?
而且email是随机生成的

**Comment by Matrixbirds** [comment]
为何不允许用户修改email?

**Comment by songjiayang** [comment]
@Matrixbirds 我也想不到不能修改的理由！

**Comment by huacnlee** [comment]
已解决，历史遗留 GitHub 登陆自动生成那种  xxx@example.com 格式的 Email 现在可以在个人设置页面修改了。

f859ebcb9008d743f974f445d89a74c05df04f18
