### ISSUE TITLE
关于登陆的placeholder问题

### ISSUE THREAD

**Issue by Matrixbirds** [ruby-china/ruby-china#395]
![登陆的placeholder](http://7xivqf.com1.z0.glb.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202015-05-04%20%E4%B8%8B%E5%8D%883.55.11.png)

用户名是否应该改成email或者注册时的邮箱?

**Comment by greatghoul** [comment]
嗯嗯，赶紧提交 PR

**Comment by huacnlee** [comment]
NO, Email 只是一个可选项，用户名才是主要的

**Comment by Matrixbirds** [comment]
那么Oauth验证的要怎么登陆呢？密码没法重置么
