### ISSUE TITLE
微信浏览器中打开ruby-china页面样式问题

### ISSUE THREAD

**Issue by songjiayang** [ruby-china/ruby-china#397]
![Uploading Screenshot_2015-05-06-10-04-43.png…](http://zuoyouba.qiniudn.com/Screenshot_2015-05-06-10-04-43.png)

**Comment by songjiayang** [comment]
@huacnlee 我的是安卓机器

**Comment by anvyzhang** [comment]
QQ X5引擎貌似对某个样式不支持，QQ浏览器一样的问题

**Comment by songjiayang** [comment]
@anvyzhang  qq浏览器有同样问题吗？如果是，那应该方便调试很多，我下载的 qq浏览器for mac 没有重现问题。

**Comment by anvyzhang** [comment]
qq浏览器for mac应该是chromium内核，android版才是X5

**Comment by songjiayang** [comment]
@anvyzhang  got it, thank you.

**Comment by ileenhow** [comment]
原来已经有人提了issue，解决方法在此
https://github.com/ruby-china/ruby-china/issues/462

**Comment by FlowerWrong** [comment]
+1

**Comment by songjiayang** [comment]
@ileenhow  何不发个 pr ？我更倾向于你给出的将  `turbolinks-progress-bar` 移到 body 上

**Comment by ileenhow** [comment]
@songjiayang progress bar是`turbolink`在html上设置before伪元素来实现的，除了修改`turbolink.js`的代码，这个`class`也不能移到body上
