### ISSUE TITLE
关于论坛部署在DigitalOcean上遇到的一些问题以及解决方法

### ISSUE THREAD

**Issue by fraserxu** [ruby-china/ruby-china#408]
1. resove the locale issue`locale-gen en_US en_US.UTF-8` and `sudo locale-gen UTF-8`

2. Permission denied while updating apt source with created user => use root user `ssh root@MYIP` and do it again and quit

3. Need `sudo` to edit `/etc/nginx/nginx.conf`

4. Install Git `apt-get install git`

5. Install dependencies `sudo apt-get install memcached mongodb redis-server imagemagick`

6. Certificate error with taobao mirror `https://ruby.taobao.org` => comment out taobao mirror because its's on DigitalOcean or just use http

7. `Incomplete response received from application`
  * Enter your app root
  * run: rake secret
  * copy the output
  * go to /yourapp/config/secrets.yml
  * set the production secret_key_base

8. App being redirect to https://xxx.xxx.xxx.xxx

Error log in nginx
```
App 32574 stdout: => Memory usage: 149.05 Mb
App 32654 stdout:
[ 2015-05-26 08:42:59.3637 32145/7f3c6372f700 Ser/Server.h:931 ]: [Client 1-3] Disconnecting client with error: client socket write error: Broken pipe (errno=32)
App 32668 stdout:

```

**Comment by fraserxu** [comment]
I follow the wiki step by step, but still can not make it work. Anyone can help?

**Comment by fraserxu** [comment]
@huacnlee 你好，请问为什么这个issue没有得到任何回复就关闭了呢？ 还是说这里鼓励使用中文提问？:)

**Comment by huacnlee** [comment]
不帮人解决部署的问题，这个项目是解决 Ruby China 的问题

**Comment by fraserxu** [comment]
部署也是这个项目的一部分吧？既然项目wiki中有提到如何去部署，当我按照说明操作失败是否应该去尝试解决？

**Comment by fraserxu** [comment]
提交这个issue的目的也是希望将自己在部署过程中遇到的问题及解决方法公开，让其他尝试部署的人可以尽量避免这些错误。:)

**Comment by huacnlee** [comment]
README 上面的教程是给开发环境用的。
你 Issue 里面提的内容都是部署 Rails 应用服务器过程、甚至 Linux 服务器的一些基本操作，这不是这个项目需要考虑的；


--  
Jason Lee


在 2015年10月15日 星期四，11:28，Fraser Xu 写道：

**Comment by fraserxu** [comment]
多谢回复。 我知道Readme上面的教程是给开发环境用的，在我本地也没有任何问题。

我上面是根据wiki里面在[ubuntu上部署的教程](https://github.com/ruby-china/ruby-china/wiki/Ubuntu-14.04-%E4%B8%8A%E4%BD%BF%E7%94%A8-Nginx-Passenger-%E9%83%A8%E7%BD%B2-Ruby-on-Rails)来操作的。

这个不是项目的一部分我可以理解。 :) 

只是希望可以去帮忙完善。
