### ISSUE TITLE
IE11下，发帖时无法选择节点

### ISSUE THREAD

**Issue by lgn21st** [ruby-china/ruby-china#425]
由用户报告，在虚拟机中测试，IE11下，点击［选择节点］无法显示下拉菜单。
![](https://ruby-china-files.b0.upaiyun.com/photo/2015/63e9cac819bbc61837ad8cf865757ca0.png)

**Comment by Go-Faram** [comment]
ubuntu 上的chrome和firefox都无法显示下拉菜单,手机上是正常的

**Comment by lgn21st** [comment]
另外一条来自用户的反馈

> 是的，用Chrome 浏览器，如果先点发布新帖，进到帖子编辑那里，就无法再选节点（下拉菜单不显示），如果在发布新帖那里点下达菜单，显示可选节点有：Gem/瞎扯淡/工具控/部署/新手问题.....

> 希望有帮助并且能解决哦！~

> 感谢！

**Comment by yinsigan** [comment]
我也是用chrome，也遇到过类似的问题

**Comment by huacnlee** [comment]
各位再试试呢，我刚才重新发布了一下，Firefox 上面的问题已经没了。

**Comment by lgn21st** [comment]
:+1: 测试了一下，在 IE11 下可以正常显示节点下拉菜单了。
