### ISSUE TITLE
Markdown 关于 blockqute 的问题

### ISSUE THREAD

**Issue by greatghoul** [ruby-china/ruby-china#426]
编辑一篇帖子时，发现了 ruby china markdown 解析的两个问题。

## 问题1：blockquote 中没有办法正确换行

```
> some text
>   <------ 此处有两个以上空格
> other text
```

使用了强制换行，但是在 blockquote 中没有被解析，但 blockquote 之外就没有问题。

## 问题2：blockquote 引用结束标志没有正确识别

```
> aaa
> bbbccc <---- 此处有换行
ccccc
```

此时 ccccc 也会被包含在 blockquote 中，不过 github 也是这样的，可能是我用法有问题吧。

**Comment by reyesyang** [comment]
1. blockquote 换行

        > some text
        > other text

2. blockquote 结束

        > aaa
        > bbbccc
        
        cccccc
