### ISSUE TITLE
[相容性] Firefox 39.0 發佈帖子時無法選擇節點(Node)

### ISSUE THREAD

**Issue by bmiwdmb** [ruby-china/ruby-china#428]
Linux/Windows 上都會出現這個問題，button dropdown 無法正確展開。

查了上游 [Bootstrap-select](http://silviomoreto.github.io/bootstrap-select/)，可以正常使用。

(圖片中黑色那條即是 dropdown 無法正確展開的樣子)

!["picture"](http://i.imgur.com/0ETBRD3.png)

**Comment by huacnlee** [comment]
已修正，再试试
