### ISSUE TITLE
帖子列表有时会丢失用户头像

### ISSUE THREAD

**Issue by greatghoul** [ruby-china/ruby-china#429]
![image](https://cloud.githubusercontent.com/assets/208966/8892055/1ac32f90-3375-11e5-9327-21d57b0b0fd2.png)

```
Google Chrome 版本 44.0.2403.107 (64-bit)
```

**Comment by Matrixbirds** [comment]
用的是七牛云存储么

**Comment by xuncheng** [comment]
![qq20151028-1](https://cloud.githubusercontent.com/assets/1650860/10778519/09bb1ece-7d62-11e5-803e-39f61a57d29c.png)

这是两种不一样的头像URL: [https://ruby-china.org/avatar/49d6f1eb55c783865ecd9c5e34ac7627.png?s=96&d=404](https://ruby-china.org/avatar/49d6f1eb55c783865ecd9c5e34ac7627.png?s=96&d=404)

**Comment by huobazi** [comment]
这是 gravatar 反向代理出问题了
