### ISSUE TITLE
topic里面@user匹配问题

### ISSUE THREAD

**Issue by FlowerWrong** [ruby-china/ruby-china#436]
![2015-08-11 00 45 54](https://cloud.githubusercontent.com/assets/5362640/9177625/cba21b22-3fc4-11e5-9be4-20b245d12d05.png)
图片中的几个@开头都被markdown当做ruby-china用户处理了，我试着修复，但我看到了这句话
[match any user even not exist.](https://github.com/ruby-china/ruby-china/blob/master/lib/markdown.rb#L174) 想问一下为什么？
另外，如果要识别哪些才是真正的ruby-china用户，就需要额外维护一个用户列表，例如缓存到redis，不知道还有没有更好的方案？

**Comment by huacnlee** [comment]
因为 @ 符号 Ruby 的写法是用 \`@foo\` 来包住，我们没法确定用户到底是想 @ 还是只是写了一个 Ruby 的类变量，所以还是当成 @ 人来处理

**Comment by FlowerWrong** [comment]
@huacnlee 
<| 如果要识别哪些才是真正的ruby-china用户，就需要额外维护一个用户列表，例如缓存到redis，不知道还有没有更好的方案？
