### ISSUE TITLE
首页上方的"社区"、"WIKI"等几个按钮名称在哪里修改？

### ISSUE THREAD

**Issue by shrekmaxi** [ruby-china/ruby-china#445]
![image](https://cloud.githubusercontent.com/assets/5965221/9795166/a654be54-5821-11e5-8d22-0b820e2ad6a8.png)

如图，我在app/views/layout/application,htm.erb文件中修改了原有的navbar-brand(原来为"RUBY CHINA"),但是却始终找不到包含"topics"的title饮用(用firebug可以看到有<a href="/topics">社区</a>的字样)，但我编辑文件时却没有发现，WHY?

**Comment by huacnlee** [comment]
全局搜索
