### ISSUE TITLE
网页bug提交,不知道是因为我的浏览器或者系统的原因,才出现这样的结果?

### ISSUE THREAD

**Issue by wsdjeg** [ruby-china/ruby-china#446]
![2015-09-13 19-56-12](https://cloud.githubusercontent.com/assets/13142418/9836605/676d75c2-5a52-11e5-8601-ccb0c32f0da2.png)

**Comment by huacnlee** [comment]
这是墙的问题

**Comment by wsdjeg** [comment]
明白了,谢谢
