### ISSUE TITLE
like改为赞可好

### ISSUE THREAD

**Issue by FlowerWrong** [ruby-china/ruby-china#452]
多个like(貌似是8)后会高亮答案, 改为类似知乎的赞可好? 
like是喜欢的意思,表达的更多是个人对这个答案的意愿,不太能表现出对作者答案价值赞赏.

**Comment by huacnlee** [comment]
+1 我觉得可以，修改一下文字而已

cc @chloerei @lgn21st

**Comment by lgn21st** [comment]
我觉得 `赞` 不错。

**Comment by huobazi** [comment]
赞 在 E 文就被翻译（当做）成 like 的
