### ISSUE TITLE
Ruby China App 所需 API 接口

### ISSUE THREAD

**Issue by DotHide** [ruby-china/ruby-china#469]
# Ruby China App 所需 API 接口
根据 Ruby China App v1.0 release 的上线功能标准，现阶段需要对 Ruby China 的 API 接口做如下调整：
> 另建议 API 文档能按分类显示，便于查询

### 1.1 获取用户详细资料 
调用地址：`[GET] /users/:login.json`
返回字段__缺少__：✅
1. 用户类型（会员、高级会员、管理员）
### (缺少接口) 1.2 用户资料更新
调用地址：`[PUT] /users/:login/profile.json`
### (缺少接口) 1.3 用户密码更新
调用地址：`[PUT] /users/:login/passwd.json`
### (缺少接口) 1.4 获取用户各类总数 ✅
调用地址：`[GET] /users/:login/counts.json`
返回字段__增加__：
1. 用户发帖数：`topics_count`
2. 用户回帖数：`replies_count`
3. 用户收藏贴数：`favorites_count`
4. 用户关注者数：`followers_count`
5. 用户正在关注数：`following_count`
### 1.5 获取用户创建话题列表
调用地址：`[GET] /users/:login/topics.json`
返回字段__删除__：
1. 用户信息 `users` （用户创建的话题，势必已经获得该用户信息，且返回列表中每个帖子的用户信息相同，建议删除，减少冗余数据）
### (缺少接口) 1.6 获取用户回帖列表
调用地址：`[GET] /users/:login/replies.json` 
返回字段__增加__：（取消）
1. 话题ID：`id`
2. 话题标题：`title`
3. 回帖内容：`body_html`
4. 回帖时间：`created_at`
5. 更新回帖时间：`updated_at`
### (缺少接口) 1.7 获取用户收藏话题列表
调用地址：`[GET] /users/:login/favorites.json`
返回字段__增加__：✅
1. 话题ID：`id`
2. 话题标题：`title`
3. 对应节点ID：`node_id`
4. 对应节点名称：`node_name`
### (缺少接口) 1.8 获取用户点赞话题的点赞状态
调用地址：`[GET] /users/:login/topic/likes.json`
传入参数：
1. 话题ID：`topic_id`
返回字段：
1. 点赞状态：`state` （ true / false ）
### (缺少接口) 1.9 获取用户点赞回帖ID列表
调用地址：`[GET] /users/:login/replies/likes.json`
返回字段：
1. 点赞回帖ID数组：`reply_ids` 
> 这么做的目的是能一次性获取所有该用户点过赞的回帖ID，减少与服务器的交互次数

### 2.1 获取话题列表
调用地址：`[GET] /topics.json`
返回字段__缺少__：
1. 建议增加帖子总数（并根据传入节点输出对应节点的帖子总数）`topics_count`
2. 置顶帖标识：`is_top` （ true / false ）
3. 优质贴标识：`is_popular` （ true / false ）✅ (excellent字段)
### 2.2 获取某个话题的回帖列表
调用地址：`[GET] /topics/:id/replies.json`
返回字段__缺少__：
1. 赞数量：`likes_count` ✅

### 3.1 获取用户通知列表
调用地址：`[GET] /notifications.json`
返回字段__缺少__：✅
- 创建话题对象（包含ID、标题、内容）：`topic` 

> 如果要把创建话题的内容显示在通知中，则需要以上对象，现在的返回结果中没有话题信息

- 回复话题标题：`reply.topic_title`

> 建议这里把标题一起带过来，省的在做一次 GET 

此外，该接口的返回结果中，只有两种文案，建议把另外三种也补充描述一下

**Comment by huacnlee** [comment]
2.1 用总数来干嘛的？

修改密码，和更新资料的接口可以暂时先不搞，等下一版本，优先实现浏览和讨论的功能

**Comment by DotHide** [comment]
要不要显示某个节点下的总帖子数呢？比如招聘节点，标题栏有共有多少个主题这种

**Comment by DotHide** [comment]
加了不少了，抽空看看

**Comment by pynixwang** [comment]
[GET] /topics/top20.json

获取首页上的20个精华贴。。。。
