### ISSUE TITLE
安装rubychina的问题

### ISSUE THREAD

**Issue by thinkloki** [ruby-china/ruby-china#479]
ruby-china安装问题，我的环境已经装好了 就是 执行rails s的时候老是出问题。

gem安装所需要的插件出问题，用淘宝的镜像也不行 。
另外，有没有稍微详细一点的安装介绍呢？
http://7xkvgl.com1.z0.glb.clouddn.com/QQ20151017-1@2x.png
http://7xkvgl.com1.z0.glb.clouddn.com/QQ20151017-0@2x.png

**Comment by kesin** [comment]
你执行`bundle install`了吗？

**Comment by thinkloki** [comment]
执行了 还是gem更新文件不成功，root用户 非root用户都执行了  
就是不行 服务器是14.04的 环境应该没问题。

**Comment by greatghoul** [comment]
看着是 nokagiri 的依赖没有安装，你仔细看上面的错误信息，是什么依赖没有安装，手工装一下再 bundle 就好了

**Comment by kesin** [comment]
你把你执行`bundle install`的结果发出来

**Comment by thinkloki** [comment]
http://7xkvgl.com1.z0.glb.clouddn.com/QQ20151019-1@2x.png
http://7xkvgl.com1.z0.glb.clouddn.com/QQ20151019-2@2x.png
http://7xkvgl.com1.z0.glb.clouddn.com/QQ20151019-3@2x.png
http://7xkvgl.com1.z0.glb.clouddn.com/QQ20151019-3@2x.png

按照文档上得来一遍，有很多得库爆红，机房是洛杉矶的机房 ,淘宝的ping 还可以，不知道到底是哪里出了问题。
http://7xkvgl.com1.z0.glb.clouddn.com/QQ20151019-3@2x.png

**Comment by kesin** [comment]
问题提示的很清楚了啊，你这是`bundle install`的时候内存不足啊……
`Cannot allocate memory - git (Errno::ENOMEM)`

给你提个意见：发帖尊重别人，做好排版，能贴出来贴出来，方便别人复制，就算贴图，也别直接发链接。

**Comment by thinkloki** [comment]
![image](https://cloud.githubusercontent.com/assets/7163155/10625957/ca96f536-77dc-11e5-8b62-c70cba2cfeee.png)

内存是512的，digitalocean的洛杉矶机房，想跑rubychina的话 需要多大的内存呢？

**Comment by thinkloki** [comment]
谢谢打架了 问题已经解决了，确实是内存的问题。
