### ISSUE TITLE
Forgor Password Spelling Mistake

### ISSUE THREAD

**Issue by ksec** [ruby-china/ruby-china#481]
The Sign in Page has "Forgor Password", it should be "Forgot".

**Comment by JuanitoFatas** [comment]
Could you open a Pull Request and fix it? :blush:

**Comment by ksec** [comment]
Ok I just tried, hope I didn't mess things up.

**Comment by JuanitoFatas** [comment]
@huacnlee Can close this issue, fixed in #482.
