### ISSUE TITLE
提议不再用 Gravatar 而是要求用户必须在 Ruby China 上传头像

### ISSUE THREAD

**Issue by huacnlee** [ruby-china/ruby-china#500]
## 意义：

1. 可以明确知道用户是否有头像，这样可以做限制，比如没头像不能发帖；
2. 可以让没头像的用户实现基于 login 第一个字母，转换成字母头像，这样没头像的用户不再会出现同一都是一种样子的问题。例如这样 ![](http://discuss.gohugo.io/letter_avatar/goyllo/50/2.png)，这个基于 letter_avatar

@ruby-china/owners 说说你们的看法

**Comment by chloerei** [comment]
我觉得可以。

**Comment by lgn21st** [comment]
我赞同。

**Comment by xiaoronglv** [comment]
线上的展示效果还挺好看的，好多人都用来做默认头像了。
