### ISSUE TITLE
登录时的验证码输入框不明确

### ISSUE THREAD

**Issue by linjunpop** [ruby-china/ruby-china#502]
![screen shot 2015-11-02 at 11 18 24](https://cloud.githubusercontent.com/assets/214616/10873718/9b8b28cc-8153-11e5-9af8-f2edbcd6a737.png)

如图，验证码的输入框和上面的用户名／密码框不一致，造成困扰

**Comment by huacnlee** [comment]
没明白你的意思

**Comment by huobazi** [comment]
那个黄颜色是 chrome 浏览器记住密码自己加的样式吧

**Comment by linjunpop** [comment]
哦，没有自动补全用户名／密码，输入框的样式就一致了
![screen shot 2015-11-02 at 14 44 15](https://cloud.githubusercontent.com/assets/214616/10875690/60398468-8170-11e5-80cf-0c4192a42bdf.png)

**Comment by linjunpop** [comment]
如果打开自动填充，那验证码那一栏确实挺困惑的
