### ISSUE TITLE
Mongoid::Errors::DocumentNotFound in JobsController#index

### ISSUE THREAD

**Issue by shrekmaxi** [ruby-china/ruby-china#515]
clone本项目之后按照wiki上的做法成功初始化ruby-china,可以正常访问，唯独有一个问题:
当我点击首页上方的"jobs"按钮之后出现如下错误,求解

![image](https://cloud.githubusercontent.com/assets/5965221/11233519/62f2562c-8df9-11e5-80c8-b8c1483264e5.png)

**Comment by huacnlee** [comment]
手工创建一个 Node 叫招聘，然后修改 Node.jobs_id 成为那个 Node 的编号

**Comment by shrekmaxi** [comment]
请问管理后台的url是什么?为何我在config.yml和config.yml.default里面将admin的e-mail改成我自己的账号邮箱却没有看到任何变化？
