### ISSUE TITLE
how to enable "jobs" node?

### ISSUE THREAD

**Issue by shrekmaxi** [ruby-china/ruby-china#516]
sorry to bother you guys. but I just don't know how to make the "jobs" node work.
I did access the cpanel(by changing admin's E-mail address to mine), and I created one sections with sort number=25 & one node with sort number=25 too.
Then I modified the jobs_controller like this:
@node = Node.find(25)

But it still doesn't work...   Can anyone help?

**Comment by huacnlee** [comment]
#515 请不要重复提交，上个 Issue 我已经回答过了
