### ISSUE TITLE
登录验证码输入错误时提示语会随机显示为不同语言

### ISSUE THREAD

**Issue by dylanninin** [ruby-china/ruby-china#518]
登录验证码输入错误时，会有『验证码不正确』提示语；多刷几次（不做其他设置变动），提示语会随机显示为不同语言，目前碰到的：

- 英文提示：『Captcha invalid!』
- 简体中文提示:『验证码不正确』
- 繁体中文在第一次请求登录时有碰到，之后刷新、请求并未重现。

截图暂时无法上传（Something went really wrong, and we can’t process that file)，稍后补充。

浏览器；Version 47.0.2526.69 beta (64-bit)

**Comment by songjiayang** [comment]
确实存在中英文提示之间跳的情况！
