### ISSUE TITLE
记事本上的一个小bug

### ISSUE THREAD

**Issue by railsfans** [ruby-china/ruby-china#519]
创建完记事本之后下面会有显示这么一行字。
11个字符，于2小时之前创建，1次修改。这个bug就是时间没有显示出来。
解决办法：在notes.coffee的init函数中增加一句话
$("abbr.timeago").timeago()

**Comment by songjiayang** [comment]
貌似这个 bug 已不存在，截图为新创建的 Note， 英文环境。 
![screen shot 2016-01-20 at 2 59 21 pm](https://cloud.githubusercontent.com/assets/1459834/12441879/77959a26-bf86-11e5-93de-29da052eb65c.png)

**Comment by railsfans** [comment]
恩，貌似被修复了，我好久之前提出的
