### ISSUE TITLE
Emoji 404 错误

### ISSUE THREAD

**Issue by hkliya** [ruby-china/ruby-china#522]
我最近 Fork 了 Ruby China，但 emoji 不能显示
我的情况是：

图片地址是：
![](http://ww3.sinaimg.cn/large/61412e43gw1ezb3ny1nfuj20jm04o0t9.jpg)

但我在 cap compile_assets 的过程中看到文件名变成 digest 的了。
![](http://ww1.sinaimg.cn/large/61412e43gw1ezb3pazxszj20ze02sq42.jpg)
Rei 提过类似问题，不知道是怎么解决的。
https://github.com/elm-city-craftworks/md_emoji/issues/5

**Comment by huacnlee** [comment]
这些文件我没有放到发布流程里面去，被忽略了，因为他们长期不会有变动的，我是独立上传文件到 CDN /assets/emojis 文件夹的

**Comment by huacnlee** [comment]
https://github.com/ruby-china/ruby-china/commit/a9182af6291f469dca1a93576bcf942609514b8d

**Comment by hkliya** [comment]
谢谢！这样我就明白。
手工上传来解决。
