### ISSUE TITLE
这个地址https://ruby-china.org/sites  打开很慢。

### ISSUE THREAD

**Issue by CCLink2008** [ruby-china/ruby-china#523]
https://ruby-china.org/sites  打开很慢，有没有和我感觉一样的。

**Comment by xiaoronglv** [comment]
取这些网站的 icon 花了不少时间，欢迎 pull request

![ruby_sites_ _ruby_china](https://cloud.githubusercontent.com/assets/1224077/12000602/a3acf70c-ab14-11e5-8ada-fab93e8e7f81.jpg)

**Comment by songjiayang** [comment]
1. 客户端连接数限制，同时获取这么多图片，确实这样，不过本地有 cache 应该好点。
2. 不过，为什么这些图片地址都是 google.com ? 这里是个可以优化的地方！

**Comment by aspirewit** [comment]
@xiaoronglv 能否提供sites的种子数据

**Comment by huacnlee** [comment]
Fixed
