### ISSUE TITLE
找回密码无法保存密码

### ISSUE THREAD

**Issue by BenZhang** [ruby-china/ruby-china#526]
当输入了新的密码以后会提示
Login name already taken

**Comment by huacnlee** [comment]
尝试了一下，没有你所说的问题，找回密码 -> 打开邮件 -> 打开修改我的密码 -> 输入新密码 -> 修改成功

**Comment by BenZhang** [comment]
我刚才又做了些尝试。发现了一个问题，就是我以前是通过邮箱注册的，后来又多手用了github login. 因为我github的邮箱跟我注册的邮箱是一样的（用户名也一样，但大小写不一样），系统为我创建了一个新的账号，覆盖了老的账号。然后就出现了如上的问题。我发现只要是跟密码有关的都会出现Login name already taken的错误提示.
