### ISSUE TITLE
建议修改一下搜索功能。

### ISSUE THREAD

**Issue by CCLink2008** [ruby-china/ruby-china#528]
1 目前搜索功能是需要鼠标点一下那个图标才会出现搜索框，能不能直接就显示搜索框呢？这样就省去了点击图标的麻烦，用户也好找一些。
2 .建议把搜索本站的功能的搜索引擎由google改成baidu的，google的在国内不翻墙的话基本打不开吧。国内的用户如果要翻墙打开也太麻烦了。增加了用户使用的难度，如果用baidu是不是会好一些呢？
另外就是搜索的时候用“window.open(url)”打开一个新的标签页比把当前页面直接导航到搜索页面是不是要好一些呢？

**Comment by xiaoronglv** [comment]
1. fxxking GFW is a fundamental skill for developers. So we can filter a lot of
garbage producers, who are unable to use VPN.
2. Google is much better than Baidu. 😊

Best regards.

Sent from my Phone.

Ryan Lv
On Tue, Jan 5, 2016 at 19:23, CCLink2008 <notifications@github.com> wrote:
1 目前搜索功能是需要鼠标点一下那个图标才会出现搜索框，能不能直接就显示搜索框呢？这样就省去了点击图标的麻烦，用户也好找一些。
2
建议把搜索本站的功能的搜索引擎由google改成baidu的，google的在国内不翻墙的话基本打不开吧。国内的用户如果要翻墙打开也太麻烦了。增加了用户使用的难度，如果用baidu是不是会好一些呢？
另外就是搜索的时候用“windowopen(url)”打开一个新的标签页比把当前页面直接导航到搜索页面是不是要好一些呢？
