### ISSUE TITLE
实现站内搜索功能，立刻马上

### ISSUE THREAD

**Issue by huacnlee** [ruby-china/ruby-china#529]
已经有很多人提过了，是时候了

**Comment by CCLink2008** [comment]
可以参考一下这个页面的实现 http://note.rpsh.net/search/，先用google ，google如果加载不了，就用baidu 。

**Comment by huacnlee** [comment]
别提 Baidu 的事情，不会用 Baidu 来实现的

**Comment by pmq20** [comment]
打算用什么实现？Elastic Search？

**Comment by huacnlee** [comment]
Sunspot + Solr  


在 2016年1月6日 星期三，11:09，P.S.V.R 写道：

**Comment by huacnlee** [comment]
#531
