### ISSUE TITLE
有了内置搜索，希望在 mobile views 里把搜索框显示出来

### ISSUE THREAD

**Issue by huobazi** [ruby-china/ruby-china#536]
手机上也需要搜索

**Comment by songjiayang** [comment]
如果要添加搜索框，那么 top bar 可能需要重新设计了, rubygem 网站那样可能是个选择。
![screen shot 2016-01-22 at 12 30 22 am](https://cloud.githubusercontent.com/assets/1459834/12486857/755ef95e-c09f-11e5-987c-f88c0d96ceb3.png)

**Comment by songjiayang** [comment]
大概画了一下，你觉得这样如何？
![close](https://cloud.githubusercontent.com/assets/1459834/12741732/13c2a532-c9ba-11e5-93e1-5a8f5237d15c.png)
![open](https://cloud.githubusercontent.com/assets/1459834/12741883/6b6ef4ce-c9bb-11e5-947e-47015b841c1f.png)

**Comment by huacnlee** [comment]
@songjiayang 这样 不好看
