### ISSUE TITLE
[Feature Request] 招聘信息按照城市分类

### ISSUE THREAD

**Issue by allenwq** [ruby-china/ruby-china#537]
希望能够提供一个功能把招聘信息按照城市分类的功能（方便那些只考虑特定城市工作的人）：
- 默认显示所有城市的招聘信息
- 用户可以通过Checkbox勾选相应的城市，页面根据用户选择对招聘信息进行过滤

**Comment by cassiuschen** [comment]
这个个人认为近期没必要，利用搜索功能完全可以代替checkbox。如果真要做倒不如把招聘的信息从一个topic变成一个独立的模型，加入城市、薪资、公司类型等选项，更方便归类。然而我并不认为Ruby China有这么大的招聘量值得这么做…

**Comment by allenwq** [comment]
@cassiuschen OK, Make sense.

**Comment by songjiayang** [comment]
也许搜索可以添加 scope, 比如 jobs: search words
