### ISSUE TITLE
切换到postgres 不指定schema么？

### ISSUE THREAD

**Issue by yingce** [ruby-china/ruby-china#545]
参考了一下database.yml 不需要指定schema么 使用默认的public还是 已经在postgres配置好的默认schema？

**Comment by songjiayang** [comment]
指定 schema 是什么意思？
1. 执行 ./bin/setup 会 copy 一份 database.yml 的，不过此时会报错，因为数据库还没建立。
2. 执行 rake db:create 再执行   ./bin/setup
3. 最后 执行 rake db:migrate
4.  目前需要 elasticsearch , 但是 setup 里面没有做本地是否安装的检验，所有需要先安装。
5. 当用户登录的时候，会出现 elasticsearch 索引报错，需要到 console 里面手动执行 User.import 。

我一路跟下来，已在本地跑起来了。

后续 setup 安装文件应该会修改的。

**Comment by yingce** [comment]
@songjiayang 
postgres 库分割不是以schema来分割的么？ 如果默认不指定schema 默认使用public的话 别的账户也可以访问你的数据内容吧(public的schema)； 也可能我想的多了， 我默认会新建一个schema给schema权限 可能我这个做法欠妥；请教下你们在生产环境中的做法

**Comment by songjiayang** [comment]
@yingce 生产环境没有用太多，我觉得这个可以设置不同 postgres 的账户，然后在 rails 的 database.yml 里面配置使用对应账户？

**Comment by yingce** [comment]
@songjiayang 这样的话我用别的账户 \c 到那个库 是可以里面内容的吧 因为公用public?

**Comment by songjiayang** [comment]
@yingce 这个是 postgres 账户管理策略吧，我觉得你可以配置授权特定账户只有特定数据的特定权限，然后这个账户需要密码访问，那么你把自己的密码管理好就行吧。

**Comment by yingce** [comment]
@songjiayang  好的 明白了 策略这个postgres好像挺深的 回头研究下 谢了

**Comment by chloerei** [comment]
单机单应用，只能本地访问。
