### ISSUE TITLE
vagrant当中，并没有安装PostgreSQL?

### ISSUE THREAD

**Issue by cqcn1991** [ruby-china/ruby-china#547]
第一次用vagrant来跑Ruby China

    $ vagrant up
    $ vagrant ssh
    $ cd /vagrant
    /vagrant $ ./bin/setup

`./bin/setup` 提示 `PostgreSQL 9.4+                                                             [No]`

看了一下，`provision.sh` 当中，也没有安装`PostgreSQL`的指令

是希望我自己安装？还是有什么别的问题？
（我应该可以看这个http://stackoverflow.com/questions/11092807/installing-postgresql-on-ubuntu-for-ruby-on-rails 来安装）

**Comment by zhangsoledad** [comment]
真的没有诶 pr一个吧

**Comment by cqcn1991** [comment]
@zhangsoledad 我Linux基本不会，不知道怎么写.sh 。。。。

**Comment by zhangsoledad** [comment]
https://github.com/ruby-china/ruby-china/pull/556
