### ISSUE TITLE
哎呀，这两个 json 后缀是手误吗？

### ISSUE THREAD

**Issue by zlx** [ruby-china/ruby-china#548]
![image](https://cloud.githubusercontent.com/assets/1835854/12536335/e8798e38-c2dc-11e5-983f-a474a54c1e83.png)

**Comment by huacnlee** [comment]
有个 Bug，原因没找到，貌似 Unicorn reload 以后会出现

**Comment by zlx** [comment]
我本地起了一个环境，没重现出这个问题
