### ISSUE TITLE
怎么才能加入你们的github组织

### ISSUE THREAD

**Issue by CoderBOBO** [ruby-china/ruby-china#579]

**Comment by huacnlee** [comment]
你可以参与翻译 Ruby 社区的英文资料，如果你感兴趣的话

**Comment by CoderBOBO** [comment]
恩可以，这样就可以加入啦么，想做点贡献

**Comment by alex-marmot** [comment]
。。求个地址，想参加。

2016-02-25 10:43 GMT+08:00 BOBO <notifications@github.com>:

**Comment by CoderBOBO** [comment]
@alex-marmot    https://ruby-china.org

**Comment by CoderBOBO** [comment]
翻译完可以在rubychina发表

**Comment by huacnlee** [comment]
https://github.com/ruby-china/rails-guides

**Comment by huacnlee** [comment]
细节可以和 @JuanitoFatas 沟通

**Comment by alex-marmot** [comment]
好的，谢谢。

2016-02-25 10:59 GMT+08:00 Jason Lee <notifications@github.com>:
