### ISSUE TITLE
Ruby China 站点修改用户资料提示“用户名已占用”

### ISSUE THREAD

**Issue by douo** [ruby-china/ruby-china#581]
页面：https://ruby-china.org/account/edit

如图所示，不作任何修改仅点击**更新资料**便提示此错，尝试更新头像后也无法**更新资料**：
![](https://ruby-china-files.b0.upaiyun.com/photo/2016/c85e724355aa2c00b73e34d9cc88af68.png)

**Comment by douo** [comment]
刚才测试了一下，用 github 账号登陆便没有问题，用账号密码登录则会出现无法更新资料。

**Comment by huacnlee** [comment]
给出你 Ruby China 账号的个人页面地址

**Comment by douo** [comment]
@huacnlee https://ruby-china.org/douo

**Comment by douo** [comment]
@huacnlee 我记得我的注册时间应该是 12 年左右，现在变成了 2015-09-15 。

**Comment by huacnlee** [comment]
已修复
