### ISSUE TITLE
精华帖链接指向 pouplar_topics 而不是 excellent_topics

### ISSUE THREAD

**Issue by hxx** [ruby-china/ruby-china#588]
发现网站有两处的 “精华帖” 指向的是 popular_topics 而不是 excellent_topics

首页的 “精华文章”
![image](https://cloud.githubusercontent.com/assets/4384971/13696707/243ba146-e7a3-11e5-90c5-ee147978fec4.png)

主题列表的 “优质帖子”
![image](https://cloud.githubusercontent.com/assets/4384971/13696820/dfc3e87e-e7a3-11e5-9598-6f90c81a54cf.png)

**Comment by songjiayang** [comment]
首先 @hxx  你是对的.

但是我不知道 如果将这两个链接地址都修改为 topics/excellent,那  topics/popular 是否还有存在的必要性,想提交 pr , 但是觉得是否想和 @huacnlee  确认下。

**Comment by huacnlee** [comment]
没必要，故意的设计，两个东西是不同的

songjiayang <notifications@github.com>于2016年3月14日周一 下午7:39写道：

**Comment by songjiayang** [comment]
@huacnlee  谢谢，我大概明白了，可以理解为 `优质帖子` 不等于 `精华帖子`对吧。 
但是首页那个 `精华帖子` 按钮的链接和文字不匹配了吧。

**Comment by hxx** [comment]
这样啊，我是因为看到精华帖子在标题后面有加宝石标记，误以为有宝石标记的地方都指向精华帖
