### ISSUE TITLE
旧账号无法删除

### ISSUE THREAD

**Issue by OneNewLife** [ruby-china/ruby-china#593]
https://ruby-china.org/onenewlife
我用旧邮箱创的号，一直都删不掉，到现在还被占用着用户名(Mars Wong)，请帮忙删除一下谢谢

**Comment by huacnlee** [comment]
用户名在删除的时候是保留的，这个规则。

如果你想换 Email，请用之前那个邮箱给我发个邮件，然后我手工给你换一下

**Comment by huacnlee** [comment]
那个账号我先给你恢复了

**Comment by OneNewLife** [comment]
邮件已发，谢谢

**Comment by huacnlee** [comment]
Email 已占用

**Comment by huacnlee** [comment]
改了,你注册了好多账号啊...

**Comment by OneNewLife** [comment]
还是不行，已占用了。。。
![qq 20160328112253](https://cloud.githubusercontent.com/assets/10388933/14070315/6fff4628-f4d7-11e5-82ee-db780fe221dc.png)

**Comment by huacnlee** [comment]
搞什么啊，不是都给你修改好了么！

https://ruby-china.org/onenewlife

**Comment by OneNewLife** [comment]
有bug，我必须要点忘记密码去重置我的密码才可以更新我的资料，现在可以用了，谢了
