### ISSUE TITLE
Ruby-china topic 阅读数量是如何统计的

### ISSUE THREAD

**Issue by wenweih** [ruby-china/ruby-china#601]
![image](https://cloud.githubusercontent.com/assets/3449692/14371183/b7078826-fd67-11e5-8402-0d728a05a43b.png)  
请问帖子的阅读数量是怎么统计的。  
我在 ```app/views/topics/_topic_info.html.erb``` partial 中找到 ```<%= topic.hits %> <%= t("common.read_times")%>```,然后在 ``app/serializers/topic_detail_serializer.rb```中追踪到 ```hits```方法。但是在```topic.rb```中也发现有一个这样的关心 ```counter :hits, default: 0```  
没看明白，请问是如何实现的呢。  
谢谢。

**Comment by songjiayang** [comment]
代码出处： https://github.com/ruby-china/ruby-china/blob/33379ada8f6a81425bd286c1d40bceb139b3a946/app/controllers/topics_controller.rb#L70

使用到的 gem https://github.com/nateware/redis-objects .

**Comment by wenweih** [comment]
@songjiayang thx
