### ISSUE TITLE
user avatar 尺寸问题

### ISSUE THREAD

**Issue by songjiayang** [ruby-china/ruby-china#605]
展示使用的是 48px，但是原图是 96px, 是否可以直接将原图变得 48 px,这样对于网络下载会减小很多，尤其移动端。
![screen shot 2016-04-14 at 11 15 13 am](https://cloud.githubusercontent.com/assets/1459834/14516118/6a381d6a-0232-11e6-945c-22dfd061d469.png)

**Comment by huacnlee** [comment]
这是为 Retina 屏幕设计的

**Comment by songjiayang** [comment]
理解了，谢谢
