### ISSUE TITLE
发帖时候，无法通过搜索选择帖子节点，点击无反应

### ISSUE THREAD

**Issue by songjiayang** [ruby-china/ruby-china#617]
如图：
![screen_shot_2016-04-25_at_11_00_08_am](https://cloud.githubusercontent.com/assets/1459834/14772827/14a48d1a-0ad5-11e6-9f70-b309afab0aa9.png)

Chrome: Version 49.0.2623.112 (64-bit)

**Comment by huacnlee** [comment]
那个是分组，用中文搜索

**Comment by songjiayang** [comment]
got it, thanks
