### ISSUE TITLE
change user city with select input

### ISSUE THREAD

**Issue by songjiayang** [ruby-china/ruby-china#628]
随着数据积累，热门城市已经有不少，那么用户在修改城市信息的时候，是否可以从已有城市中选择呢，如果无则创建新的。

![screen shot 2016-05-05 at 4 02 58 pm](https://cloud.githubusercontent.com/assets/1459834/15038968/388653ea-12db-11e6-9742-cafb9b91c120.png)

**Comment by huacnlee** [comment]
无关紧要的功能，暂时不动

**Comment by songjiayang** [comment]
👌
