### ISSUE TITLE
fluidbox-ghost position issue

### ISSUE THREAD

**Issue by songjiayang** [ruby-china/ruby-china#635]
system: ubuntu
browser: chrome
问题描述：

访问连接， https://ruby-china.org/topics/29960 ，点击放大图片
![2016-05-10 09-43-42](https://cloud.githubusercontent.com/assets/1459834/15133335/673557d8-1694-11e6-83e2-0f408031e290.png)
原图

![2016-05-10 09-50-33](https://cloud.githubusercontent.com/assets/1459834/15133370/b442ec20-1694-11e6-95bf-071766b17353.png)
Ruby-China 放大图

放大图片有部分被网站顶部导航条挡住了

期望: 放大图片应该有个 margin top，显示完整图片

**Comment by huacnlee** [comment]
z-index 的问题，看起来是
