### ISSUE TITLE
每天新增用户人数

### ISSUE THREAD

**Issue by ming-relax** [ruby-china/ruby-china#661]
我想要得到 ruby-chin 每天的新增人数，主要是想对 ruby 程序员的增长人数做统计；没有看到任何 api 实现这个功能。我自己开 PR 的话会被接受吗？

ruby-china 社区对这样的 PR 欢迎吗？

**Comment by songjiayang** [comment]
感觉这个功能需求比较少，可以每天自己爬虫看一下即可。

**Comment by huacnlee** [comment]
这个不行

**Comment by ming-relax** [comment]
嗯，好像通过这里就可以看到 https://ruby-china.org/users
