### ISSUE TITLE
没有分类可选了？

### ISSUE THREAD

**Issue by cqcn1991** [ruby-china/ruby-china#665]
![qq](https://cloud.githubusercontent.com/assets/2425141/15573591/a9d3d464-237a-11e6-9ae6-8b1899fbeb82.png)

点击之后

![qq 2](https://cloud.githubusercontent.com/assets/2425141/15573602/b9c0611c-237a-11e6-95bd-b1dc77f14240.png)

**Comment by songjiayang** [comment]
这是个 bug

**Comment by songjiayang** [comment]
@cqcn1991 已修复，感谢反馈。
