### ISSUE TITLE
关于 like 的问题

### ISSUE THREAD

**Issue by songjiayang** [ruby-china/ruby-china#669]
问题描述：

自己的帖子，后端设计是不能 like 的，但是前端没有做判断，应该给出提示或者禁用 like 按钮，不然会出现如下问题：

![screen shot 2016-05-28 at 10 11 50 am](https://cloud.githubusercontent.com/assets/1459834/15624903/37d13786-24c8-11e6-8a64-5d71168deead.png)

![screen shot 2016-05-28 at 11 36 52 am](https://cloud.githubusercontent.com/assets/1459834/15624920/81220e06-24c8-11e6-92d7-2236fb0cbb43.png)

自己帖子点击 like, 显示 like +1， 但页面刷新，like 状态丢失。

解决办法:

1.  作为错误提醒, 比如：自己帖子不能 like
2.  禁用 like 按钮不能发送请求。
3. 修改后端逻辑，自己帖子也能 like 就像收藏一样，自己帖子也可以收藏

@huacnlee 你觉得呢？

**Comment by huacnlee** [comment]
这个不影响，就没必要限制掉，弄得前端也很复杂，限制的目的已经达到了
