### ISSUE TITLE
关于左侧收藏的 UI 颜色 

### ISSUE THREAD

**Issue by songjiayang** [ruby-china/ruby-china#670]
目前UI:
![screen shot 2016-05-28 at 11 45 06 am](https://cloud.githubusercontent.com/assets/1459834/15624964/cf6136fe-24c9-11e6-9c5f-e2d29c517cd3.png)

期望 UI :

![screen shot 2016-05-28 at 11 45 25 am](https://cloud.githubusercontent.com/assets/1459834/15624965/cf88ade2-24c9-11e6-87a1-4dc07d7fa267.png)

目的： UI 统一性

**Comment by huacnlee** [comment]
按钮是 Switch 的概念，而赞不是
