### ISSUE TITLE
生成帖子的 URL 二维码，参照 testerhome.com 社区的实现

### ISSUE THREAD

**Issue by lgn21st** [ruby-china/ruby-china#702]
方便将好文章分享到微信朋友圈。

![screen_shot_2016-07-20_at_ 1_20_27](https://cloud.githubusercontent.com/assets/7104/16959599/72cf2af4-4e18-11e6-9ba1-0608948ff923.png)

**Comment by songjiayang** [comment]
这个以前提过 issue, 被关闭了，我也支持功能

**Comment by songjiayang** [comment]
已发布 WeChat 分享
