### ISSUE TITLE
帐号登录，默认不需要验证码

### ISSUE THREAD

**Issue by songjiayang** [ruby-china/ruby-china#703]
需求：

```
不管有用还是能被破，用户体验是极差的，有时候我都要输两三次。

建议学 Google，如果连续几次输入错误，再出现验证码防刷。

或者只要一次输入有误，就弹出验证码，这样的用户体验也是好得无比的，因为很多用户都是用 Lastpass 之类的密码管理软件。

```

来源链接 ：https://ruby-china.org/topics/30571#reply9

**Comment by xiaoronglv** [comment]
What about this? www.jianshu.com/sign_in

Best regards.

Sent from my Phone.

Ryan Lv
On Wed, Jul 20, 2016 at 18:29, songjiayang <notifications@github.com> wrote:
需求：

不管有用还是能被破，用户体验是极差的，有时候我都要输两三次。

建议学 Google，如果连续几次输入错误，再出现验证码防刷。

或者只要一次输入有误，就弹出验证码，这样的用户体验也是好得无比的，因为很多用户都是用 Lastpass 之类的密码管理软件。



来源链接 ： https://ruby-china.org/topics/30571#reply9 [https://ruby-china.org/topics/30571#reply9]

**Comment by songjiayang** [comment]
个人不喜欢简书那种，虽然很多网站都用的它（第三方服务？），感觉整体风格不够简洁（比较 low , sorry 也许我品味问题。

**Comment by huacnlee** [comment]
我也觉得那样很 Low

**Comment by m0ur3n** [comment]
Google 那个“我不是机器人”的验证应该是比较好的方式，不过用 Google 服务的话对于没翻墙的情况就不太方便。

所以，感觉还是通过判断错误次数来实现比较好。错了3次，就开始要求输入验证码应该比较合适了吧？

**Comment by xiaoronglv** [comment]
样式确实有点丑，如果可以定制样式就好了。

上次简书的 Larry 说，他们用了这个滑条后，从未被攻破。所以一直忠心的付费，哈哈。

**Comment by songjiayang** [comment]
现在讨论的不是被攻破的问题，而是干扰了用户登录。
