### ISSUE TITLE
optional! 方法的xiao bug

### ISSUE THREAD

**Issue by menghuanwd** [ruby-china/ruby-china#705]
文件 /app/controllers/api/v3/application_controller.rb

def optional!(name, opts = {})
  if params[name].blank? && opts[:require] == true
    raise ActionController::ParameterMissing.new(name)
  end

  if opts[:values] && params[name].present?
    values = opts[:values].to_a
    if !values.include?(params[name]) && !values.include?(params[name].to_i)
      raise ParameterValueNotAllowed.new(name, opts[:values])
    end
  end

  if params[name].blank? && opts[:default].present?
    params[name] = opts[:default]
  end
end

if params[name].blank? && opts[:default].present?
如果这个参数的类型是Boolean, 且默认值是false, 则opts[:default].present? 为 false

建议改成 if params[name].blank? && opts[:default].to_s.present。

**Comment by songjiayang** [comment]
这里只需要判断有没有 default key 而不关心其值，那么可以使用 
```
opts.has_key?(:default)
```

**Comment by xuebingli** [comment]
[这段代码现在长这样](https://github.com/ruby-china/ruby-china/blob/master/app/controllers/api/v3/application_controller.rb#L46-L48)。
```ruby
if params[name].blank? && opts[:default].present?
  params[name] = opts[:default]
end
```
如@menghuanwd所言，存在小bug。于是@songjiayang 建议改成这样
```ruby
if params[name].blank? && opts.has_key?(:default)
  params[name] = opts[:default]
end
```
这段代码要做的，就是在`name`对应的值未给定时，如果存在`default`，就用`default`。实现这个功能，俺觉得其实不用三行代码，一行就行。
```ruby
params[name] ||= opts[:default]
```

**Comment by songjiayang** [comment]
params[name] ||= opts[:default] it's ok
