### ISSUE TITLE
使用Docker搭建开发环境

### ISSUE THREAD

**Issue by xuebingli** [ruby-china/ruby-china#713]
建议支持通过Docker（和Docker Compose）来搭建开发环境。相较于现有的Vagrant，优势有
- 更快。开发环境从无到有，只需要一条命令`docker-compose up`。占用资源少，运行更快。
- 更高。容器比虚拟机逼格更高。
- 更强。详情请参见[这个StackOverflow问题](http://stackoverflow.com/questions/16647069/should-i-use-vagrant-or-docker-for-creating-an-isolated-environment)。Docker作者在那个问题回复说

> The short answer is that if you want to manage machines, you should use Vagrant. And if you want to build and run applications environments, you should use Docker.

**Comment by huacnlee** [comment]
提 PR
