### ISSUE TITLE
修改个人信息出错

### ISSUE THREAD

**Issue by DoctorQ** [ruby-china/ruby-china#718]
# 描述

个人信息中修改地区、公司信息报用户名已存在的错误，无法修改。

# 截图

![87dd753f-b0cc-4905-91f8-0866d62f55b8](https://cloud.githubusercontent.com/assets/4489853/17843360/b18461cc-685f-11e6-9532-8a30a1702c9e.png)

**Comment by huacnlee** [comment]
你的帐号弄好了，有两个同名的，删除了一个
