### ISSUE TITLE
topics_count 数量不准确

### ISSUE THREAD

**Issue by vincent178** [ruby-china/ruby-china#722]
@huacnlee 你好，我在做 https://github.com/vincent178/ruby-china-mobile/ 这个过程中发现 用户的topics_count 不准确。

例如，@xiaoronglv 的 topics_count 是160， 但是用 api https://ruby-china.org/api/v3/users/xiaoronglv/topics.json 最多只能加载出来158条数据，请问下这个是什么原因？

**Comment by huacnlee** [comment]
各种 counter 的字段本来就不是一定精确的，这个只是象征性在某些地方用一下，我们之前的各种设计是不关系这个值是否精确

**Comment by huacnlee** [comment]
顺便说一下，不用浪费时间搞你哪个项目，没有价值

我们新作的 iOS 客户端以及非常好用了

**Comment by vincent178** [comment]
客户端功能好多啊，cool。

我觉得这个counter的字段不准确还是有些恼人的。比如帖子回复功能：现在ruby-china处理回复的时候是一次性全部加载，但api是有加载限制的, 那么在处理分页加载的时候，逻辑是判断已经加载的数量小于replies_count ，就会以为还有些内容没有全部加载完，会去尝试继续加载，然而并不会返回什么内容。

我现在做了一点处理，用这个`Math.ceil(topic.replies_count/20-1)*20`数字来作为比较， 20是一次加载的数量，我假设数据不会差20~~，暂时看来还没遇到什么问题。

**Comment by huacnlee** [comment]
换一个思路加载数据
