### ISSUE TITLE
无法修改个人资料

### ISSUE THREAD

**Issue by chloerei** [ruby-china/ruby-china#723]
<img width="357" alt="2016-08-25 14 32 57" src="https://cloud.githubusercontent.com/assets/49931/17959125/e6afd2b4-6ad0-11e6-8bd5-a94f3fa06a2b.png">

进入个人资料页面，什么都不修改，提交就显示名字冲突。

**Comment by huacnlee** [comment]
重复数据
我上去删除一下

**Comment by huacnlee** [comment]
好了

**Comment by marswong** [comment]
@huacnlee 
同样的问题，之前一直没管，请帮忙清了我的数据吧，我重新注册个账号好了，用户名：OneNewLife，邮箱：marswong618@gmail.com。

谢啦：）

**Comment by huacnlee** [comment]
@marswong 好了

**Comment by marswong** [comment]
@huacnlee 
还是提示 Email 已占用

**Comment by huacnlee** [comment]
我直接给你改了

**Comment by marswong** [comment]
可以帮我将 marswong618@gmail.com 的用户名改成 marswong 么？

**Comment by huacnlee** [comment]
你要干嘛，一次说完，我修改了两次了

Mars Wong <notifications@github.com>于2017年6月28日周三 下午4:41写道：

**Comment by marswong** [comment]
就是我删除账号之后 email 对应的数据还是会保存下来，导致我没法重新注册，可以帮忙把 `marswong618@gmail.com` 对应的用户名改成 `marswong` 么，谢啦：）

**Comment by huacnlee** [comment]
https://ruby-china.org/onenewlife

这个账号是老的，你需要通过邮箱找回密码的方式弄回账号。
