### ISSUE TITLE
奇怪，线上 weixin dialog footer 提示信息缺失，但本地可以

### ISSUE THREAD

**Issue by songjiayang** [ruby-china/ruby-china#753]
本地：
![screen shot 2016-09-21 at 10 21 06 pm](https://cloud.githubusercontent.com/assets/1459834/18714956/0057ac80-804a-11e6-9d37-7855c53a5cb9.png)

线上：
![screen shot 2016-09-21 at 10 21 15 pm](https://cloud.githubusercontent.com/assets/1459834/18714957/00613958-804a-11e6-9f51-a1a2ce522af2.png)

暂时找不到原因 😳

**Comment by huacnlee** [comment]
靠，搞晕了，今晚

这个问题看来是 JS 实现的问题，看起来和 Turbolinks 有关

**Comment by songjiayang** [comment]
不太可能，应该是页面缓存，我发现有些页面还没有 wexin button  

比如  https://ruby-china.org/topics/30946

**Comment by songjiayang** [comment]
sorry, check again, 是浏览器缓存，更新浏览器后，没有这个问题了，可以关闭
