### ISSUE TITLE
每访问一个帖子，帖子会被修改，就会触发一次 elasticsearch index, 这个代价是不是太大？

### ISSUE THREAD

**Issue by songjiayang** [ruby-china/ruby-china#754]
感觉可以考虑在 after_update 里面判断下修改的字断？
https://github.com/ruby-china/ruby-china/blob/master/app/models/concerns/searchable.rb#L7

**Comment by huacnlee** [comment]
访问的时候 Topic 不回被修改的呀！

**Comment by songjiayang** [comment]
是这样的，我本地 elasticsearch 没启动，访问帖子就详情就报错了，所以我以为帖子被修改了

**Comment by songjiayang** [comment]
确实不会更新，我的错误， closed
