### ISSUE TITLE
当前设置新手用户不能在 22:00 ~ 9:00 发帖。 

### ISSUE THREAD

**Issue by cqcn1991** [ruby-china/ruby-china#755]
![qq](https://cloud.githubusercontent.com/assets/2425141/18715683/bb065034-804c-11e6-9f6b-f5c384ce49d7.png)

然而。。。我已经注册好几年了啊.....
https://ruby-china.org/cqcn1991

**Comment by songjiayang** [comment]
已修复

**Comment by huacnlee** [comment]
现在还有么？ @cqcn1991

**Comment by cqcn1991** [comment]
@huacnlee 靠，这么快！？不至于代码就部署了吧。难道是我帐号的问题？
然而，我看到还是一样的...

**Comment by songjiayang** [comment]
我访问 ruby-china 貌似还不能回帖。。。

**Comment by songjiayang** [comment]
确定这个应该是 chrome 本地  cache, 试试清空本地静态文件测试，我这边清空后就可以回复了。

感觉这个 etag 是不是设计不合理？

**Comment by huacnlee** [comment]
etag 哪里是有个小 Bug，因为没有把这个条件包含进去

**Comment by huacnlee** [comment]
我本打算去掉那行的，但想象涉及到的人又比较少，相对来说带来的好处更多，所以还没有删掉

**Comment by songjiayang** [comment]
cool, 找到原因就好，不然今晚都会纠结的, 😄

**Comment by huacnlee** [comment]
不是的，出 Bug 比较奇怪，到目前为止，后台配置的 Setting.reject_newbie_reply_in_the_evening 还是 'false'

**Comment by yakjuly** [comment]
我今天遇到了 打开页面 已经有session了 提示新手不能回复。退出后重新登陆就正常。
可能和session有关？

**Comment by cqcn1991** [comment]
@songjiayang @huacnlee 啥都没干。已经好了...

**Comment by huacnlee** [comment]
原因:

#741 重构了 `@user.state` 成 Rails enum，序列化的值和之前有差别，而线上数据绝大多数用户都有 Cache 的，于是旧 cache 里面的 state 和新的 Rails enum 规则不符，导致 `@user.normal?` 是 false

而你们突然自己好了，原因是无意中出发了 User update 似的 cache 失效了。
