### ISSUE TITLE
弹出微信框左下角出现 undefined

### ISSUE THREAD

**Issue by cgg5207** [ruby-china/ruby-china#760]
![f6537248-2833-49f3-a183-e548adad5ab9](https://cloud.githubusercontent.com/assets/523974/18870470/5445ceec-84e3-11e6-8e25-2296c3515de6.png)

**Comment by songjiayang** [comment]
貌似这个应该是 cache 缘故，本地暂时没有重现这个问题。

根据 share-button 的最新代码， wechat 那个按钮会增加一个叫做 data-wechat-footer 的属性，但是渲染出来的页面却没有。
