### ISSUE TITLE
点选 [所有节点] 前后，页面 layout width 不一致

### ISSUE THREAD

**Issue by lgn21st** [ruby-china/ruby-china#777]
操作系统: macOS 10.12
浏览器：Safari Version 10.0 (12602.1.50.0.10)

下面是截图，上半部分是没有点选之前，下半部分是点选之后，页面 layout 宽度不一致。

![screen shot 2016-10-18 at 4 45 53 pm](https://cloud.githubusercontent.com/assets/7104/19470627/cbedc844-9552-11e6-8d7c-19a7a2b7c18e.png)

**Comment by lgn21st** [comment]
无法重现。

**Comment by greatghoul** [comment]
http://recordit.co/3UnqO72cWG

点选所有节点时，导航栏有错位。
Version 54.0.2840.98 (64-bit)
