### ISSUE TITLE
一直无法发帖

### ISSUE THREAD

**Issue by morpheus1984** [ruby-china/ruby-china#779]
在ruby-china注册后一直都是显示：
当前设置新手用户不能在 22:00 ~ 9:00 发帖。

无论什么时间段

账号：morpheus1984@yeah.net

**Comment by chloerei** [comment]
注册后不就是新手吗？

**Comment by huacnlee** [comment]
不知道为何，你的账号在后台显示被删除了，我给你恢复了

**Comment by morpheus1984** [comment]
谢谢
